import { useEffect, useMemo, useRef, useState } from 'react'
import { useRoom, type GameEvent } from './game/useRoom'
import './App.css'

type Tab='lounge'|'tea'|'mystery'|'guess'|'mafia'|'pacheesa'
type Room=ReturnType<typeof useRoom>
type Player={id:string;name:string}
const games:Array<[Tab,string,string,string]>=[['mystery','Motive','Solve a case together','✦'],['guess','Guess the Person','Give hints. Guess right.','?'],['mafia','Mafia & Doctor','Trust nobody after dark.','☾'],['pacheesa','Pacheesa','Raise, reset, survive.','5']]

export default function App(){
  const[draft,setDraft]=useState('')
  const[name,setName]=useState('')
  if(!name)return <main className="join"><form className="join-card" onSubmit={e=>{e.preventDefault();setName(draft.trim()||'Guest')}}><span>✦</span><p>THE COMMON LOUNGE</p><h1>Your corner of the internet.</h1><b>Games, gossip, bad alibis, and the people you like best.</b><input autoFocus value={draft} placeholder="Your name" onChange={e=>setDraft(e.target.value)}/><button>Come in →</button></form></main>
  return <Lounge name={name}/>
}

function Lounge({name}:{name:string}){
  const[tab,setTab]=useState<Tab>('lounge')
  const room=useRoom(name)
  const[message,setMessage]=useState('')
  const[tea,setTea]=useState<string[]>([])
  const[pin,setPin]=useState('')
  const send=()=>{if(message.trim()){room.sendChat(message);setMessage('')}}
  return <main className="lounge"><aside><div className="logo">✦ <b>COMMON<br/>LOUNGE</b></div><p className="roomcode">ROOM · {room.code}</p><nav><button className={tab==='lounge'?'active':''} onClick={()=>setTab('lounge')}>⌂ The lounge</button><button className={tab==='tea'?'active':''} onClick={()=>setTab('tea')}>☕ Tea board</button><p>PLAY TOGETHER</p>{games.map(([id,title,,icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><i>{icon}</i>{title}</button>)}</nav><div className="online"><span className={room.connected?'':'off'}/> {room.connected?`${room.peers.length+1} friends around`:'connecting…'}</div></aside><section className="main"><header><div><p>{tab==='lounge'?'WELCOME BACK':tab.toUpperCase()}</p><h1>{tab==='lounge'?'Hey, '+name+'!':games.find(x=>x[0]===tab)?.[1]||'Tea Board'}</h1></div><button className="invite" onClick={async()=>{await navigator.clipboard?.writeText(location.href);alert('Invite link copied!')}}>⧉ Invite friends</button></header>
  {tab==='lounge'&&<Home setTab={setTab} room={room} message={message} setMessage={setMessage} send={send}/>}
  {tab==='tea'&&<Tea tea={tea} pin={pin} setPin={setPin} add={()=>{if(pin.trim()){setTea([pin,...tea]);room.sendChat('☕ TEA: '+pin);setPin('')}}}/>}
  {tab==='mystery'&&<Mystery room={room}/>} {tab==='guess'&&<Guess room={room} me={{id:room.id,name}}/>}{tab==='mafia'&&<Mafia room={room} me={{id:room.id,name}}/>}{tab==='pacheesa'&&<Pacheesa room={room} me={{id:room.id,name}}/>}</section></main>
}

function Home({setTab,room,message,setMessage,send}:{setTab:(t:Tab)=>void;room:Room;message:string;setMessage:(s:string)=>void;send:()=>void}){return <><section className="welcome"><div><span>TONIGHT'S MOOD</span><h2>Stay in. Spill something.<br/>Play a game.</h2><p>The lounge is yours. Pick something and pull everyone in.</p></div><div className="glow">☕</div></section><div className="game-cards">{games.map(([id,title,sub,icon])=><button key={id} onClick={()=>setTab(id)}><i>{icon}</i><b>{title}</b><small>{sub}</small><em>Open →</em></button>)}</div><section className="chatbox"><h2>Live room chat <i>say hi</i></h2><div className="messages">{room.messages.length===0&&<p className="muted">No messages yet. Break the ice.</p>}{room.messages.slice(-8).map(m=><p key={m.id}><b>{m.name}</b> {m.text}</p>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Say something to the room…"/><button>Send</button></form></section></>}
function Tea({tea,pin,setPin,add}:{tea:string[];pin:string;setPin:(s:string)=>void;add:()=>void}){return <><section className="tea-hero"><span>☕</span><div><h2>Tea board</h2><p>Low stakes gossip. High stakes reactions.</p></div></section><form className="pin-form" onSubmit={e=>{e.preventDefault();add()}}><input value={pin} onChange={e=>setPin(e.target.value)} placeholder="What's the tea?"/><button>Pin it ✦</button></form><div className="pins">{tea.map((x,i)=><article className={'pin p'+i%4} key={x}><span>☕ HOT TEA</span><p>{x}</p><small>♡ {i+2} reactions · reply</small></article>)}</div></>}

type Case={title:string;place:string;hook:string;victim:string;culprit:string;suspects:{name:string;line:string}[];evidence:string[];witnesses:string[];solution:string}
const cases:Case[]=[
  {title:'The Last Slice at Marigold Café',place:'MARIGOLD CAFÉ · 9:40 PM',victim:'Dev Malhotra, food critic',hook:'Dev collapsed after stealing the last slice of lemon cake. Every person at the table had a reason to want his review buried.',culprit:'Naina',suspects:[{name:'Naina',line:'I iced the cake, sure. I never touched his plate after six.'},{name:'Kabir',line:'Dev and I argued. That is not the same as poisoning him.'},{name:'Meera',line:'I was washing glasses. Ask anyone near the sink.'},{name:'Rohan',line:'He ate my slice by mistake. I thought it was funny.'}],evidence:['A sugar packet beside Dev is glued shut with lemon syrup.','The poison reacts badly with heat; it had to be added after baking.','Naina says she left at six, but her parking receipt reads 9:31.','Dev texted: “The baker wants me to change tomorrow’s review.”','Only one clean dessert fork remains, hidden in Naina’s tote.'],witnesses:['The dishwasher saw someone in a yellow scarf return to the kitchen.','A cyclist heard Dev say, “You cannot buy five stars.”','The waiter remembers Naina insisting on carrying the final plate.'],solution:'Naina returned after closing and brushed poison onto Dev’s fork. She hid it, but the syrup and parking receipt put her back in the café.'},
  {title:'Murder Between the Margins',place:'CITY LIBRARY · 6:15 PM',victim:'Anil Bose, rare-book dealer',hook:'Anil was found in a locked reading room with a torn page in his fist and four people insisting they never went upstairs.',culprit:'Tara',suspects:[{name:'Tara',line:'I catalogued downstairs all evening. The cameras will show it.'},{name:'Imran',line:'He owed me money, but I wanted him alive to pay it.'},{name:'Leela',line:'I came for a first edition, not a fight.'},{name:'Vikram',line:'The alarm went off while I was in the courtyard.'}],evidence:['The upstairs camera loops the same eleven seconds.','A brass book cart key is missing from Tara’s chain.','The torn page lists a forged book Tara authenticated.','Dust on the fire stairs is disturbed by narrow boots.','A cup of cardamom tea is still warm behind the catalogue desk.'],witnesses:['A student heard the book cart rattle upstairs during the alarm.','The guard saw Tara’s desk empty for roughly seven minutes.','Leela noticed fresh rainwater on the fire-stair landing.'],solution:'Tara looped the camera, used the book-cart key and escaped down the fire stairs after confronting Anil about the forgery list.'},
  {title:'The Monsoon Wedding Alibi',place:'GULMOHAR PALACE · 11:05 PM',victim:'Arjun Sethi, the groom’s uncle',hook:'Fireworks covered a shout from the old music room. By the time the family reached it, Arjun was dead and the wedding necklace was gone.',culprit:'Rhea',suspects:[{name:'Rhea',line:'I was fixing the bride’s veil with twenty people around me.'},{name:'Sameer',line:'Arjun threatened me, but I never left the dance floor.'},{name:'Pooja',line:'I was checking the gift envelopes.'},{name:'Neil',line:'I set off the fireworks. My hands were full.'}],evidence:['A pearl from the necklace is caught in a veil pin.','The music-room clock was moved ahead by eight minutes.','Rhea’s voice note contains the first firework before she claims to be upstairs.','A wet heel mark matches the bridal suite slippers.','Arjun had discovered missing money in Rhea’s wedding accounts.'],witnesses:['The photographer’s group picture at 10:57 has no Rhea in it.','A child saw “the veil aunty” hurry through the rain.','The drummer remembers Sameer dancing through the entire fireworks set.'],solution:'Rhea shifted the clock to manufacture a timeline, took the necklace to cover missing funds, and pinned the veil only after returning.'},
  {title:'Static on Platform Four',place:'NIGHT TRAIN · 1:20 AM',victim:'Maya Rao, radio host',hook:'Maya’s final broadcast cut to static inside a moving sleeper train. Her compartment was bolted, but her recorder kept running.',culprit:'Omar',suspects:[{name:'Omar',line:'I was asleep in the berth opposite. The attendant woke me.'},{name:'Jiya',line:'Maya planned to expose me on air. I begged her not to.'},{name:'Pranav',line:'I checked tickets at midnight and moved on.'},{name:'Saloni',line:'I was recording rain sounds near the pantry.'}],evidence:['The bolt can be pulled shut from outside with recording tape.','Omar’s headphones contain a torn strip of that tape.','Maya’s recorder captures a station announcement at 1:07.','Omar’s ticket was scanned on the platform at 1:10.','A draft email says Maya found plagiarism in Omar’s podcast.'],witnesses:['The tea seller served Omar after the train had stopped.','A passenger saw a headphone cable under Maya’s door.','The attendant says Jiya stayed in the dining car crying.'],solution:'Omar boarded again after the announcement, killed Maya, then used tape through the door gap to slide the bolt and fake a locked compartment.'},
  {title:'A Portrait in Wet Paint',place:'ASTER GALLERY · 8:50 PM',victim:'Farah Mir, gallery owner',hook:'Farah vanished during a private viewing. Minutes later her silhouette appeared beneath a newly painted mural.',culprit:'Eshan',suspects:[{name:'Eshan',line:'I mixed the blue paint, then went outside for air.'},{name:'Diya',line:'Farah was selling my work without permission.'},{name:'Harsh',line:'I guarded the front door. Nobody left.'},{name:'Mina',line:'I spent the blackout looking for my phone.'}],evidence:['The mural’s blue layer contains theatre quick-dry additive.','Eshan bought that additive the same afternoon.','A paint roller hides a strand from Farah’s red scarf.','The loading lift was disabled from the studio switch.','Farah planned to replace Eshan as lead artist.'],witnesses:['A neighbour heard the lift move once before it stopped.','Mina saw blue paint already drying on Eshan’s cuff.','The caterer confirms Diya never left the crowded bar.'],solution:'Eshan used quick-dry paint to cover Farah’s body in the planned mural and disabled the lift so nobody could inspect the wall closely.'},
  {title:'The Midnight Voice Note',place:'LAKE HOUSE · 12:03 AM',victim:'Kunal Jain, startup founder',hook:'Everyone received a voice note from Kunal at midnight. The doctor says he had already been dead for nearly an hour.',culprit:'Sana',suspects:[{name:'Sana',line:'He sent that message himself. You all heard him.'},{name:'Aditya',line:'We fought over the company, then I took the boat out.'},{name:'Mitali',line:'I was asleep with my phone on silent.'},{name:'Zoya',line:'I made tea and stayed by the fireplace.'}],evidence:['The voice note has a clean splice after Kunal says “midnight.”','Sana edits the company podcast on the same software.','A smart speaker logged playback at 11:58, not a live voice.','Kunal’s watch stopped at 11:06.','His will removed Sana from control of the company.'],witnesses:['A fisherman saw Aditya’s boat circling the far buoy.','Zoya heard Sana testing the speaker before dinner.','Mitali woke to the click of the study door at 11:10.'],solution:'Sana edited an old recording and scheduled it through the smart speaker, giving herself a false midnight timeline.'},
  {title:'Snowed In at Cedar Lodge',place:'CEDAR LODGE · 7:30 AM',victim:'Professor Dutt, mountaineer',hook:'A blizzard sealed four guests inside. At breakfast the professor was gone, but his boots were still drying by the fire.',culprit:'Aarav',suspects:[{name:'Aarav',line:'No one could go outside in that storm. That includes me.'},{name:'Nisha',line:'He stole my research and called it collaboration.'},{name:'Bela',line:'I slept in the room beside his.'},{name:'Thomas',line:'I kept the generator alive all night.'}],evidence:['A trail begins at the wood-shed door, not the front entrance.','Aarav’s left boot has a freshly replaced sole.','The professor’s room contains a map to a disputed climbing route.','Generator logs place Thomas downstairs every twenty minutes.','Snow inside Aarav’s coat pocket has cedar splinters in it.'],witnesses:['Bela heard the wood-shed latch at 4:10.','Nisha was on a video call until 4:30.','A rescue pilot saw one torch near the ravine before dawn.'],solution:'Aarav wore spare boots, led the professor out through the wood shed, and returned before the new snowfall covered most of the trail.'},
  {title:'The Missing Reel',place:'REGAL CINEMA · 10:25 PM',victim:'Mahesh Kapoor, film archivist',hook:'A restored film ended with twenty seconds nobody had seen before. The projection stopped, and Mahesh was found behind the screen.',culprit:'Ira',suspects:[{name:'Ira',line:'I never entered the projection booth.'},{name:'Yusuf',line:'Mahesh fired me, so yes, I was angry.'},{name:'Cam',line:'I stayed in the aisle repairing a speaker.'},{name:'Neha',line:'I watched from the balcony alone.'}],evidence:['The missing reel canister has fresh purple nail varnish on its clasp.','Ira wears the same custom shade.','A booth access card was copied at 9:52.','The final frames show Ira’s father setting a historic studio fire.','Mahesh’s glasses were crushed near the screen pulley.'],witnesses:['The usher saw Yusuf outside smoking at 10:20.','Cam’s repair appears continuously on the lobby camera.','Neha heard someone descend the booth ladder in heels.'],solution:'Ira copied the access card, stole the reel that exposed her father, and used the screen pulley during the confrontation with Mahesh.'},
  {title:'Death at the Quiz Table',place:'THE OWL PUB · 9:12 PM',victim:'Ritesh Shah, quiz champion',hook:'Ritesh answered the final question, drank from the winners’ cup, and collapsed before the scoreboard changed.',culprit:'Gauri',suspects:[{name:'Gauri',line:'I wrote the questions. I did not touch the prize cup.'},{name:'Ben',line:'He cheated last season. I only wanted him disqualified.'},{name:'Lata',line:'I served drinks, not trophies.'},{name:'Mohan',line:'I was keeping score in full view.'}],evidence:['The winners’ cup was stored beside Gauri’s question cards.','A bitter almond smell clings to a felt-tip pen cap.','Gauri crossed out the original final answer minutes before play.','Ritesh had proof that Gauri sold questions to another team.','Lata’s fingerprints are on every glass but not the cup.'],witnesses:['Mohan saw Gauri lean over the trophy shelf.','Ben was arguing outside when the final round began.','A regular remembers Gauri insisting Ritesh use the cup.'],solution:'Gauri coated the rim with poison hidden in a marker cap and rewrote the last question so she could predict exactly who would drink.'},
  {title:'The Clockmaker’s Thirteenth Chime',place:'OLD CLOCK SHOP · 1:00 AM',victim:'Mr. Sen, clockmaker',hook:'The tower clock chimed thirteen times. On the final strike, the shop lights came on and Mr. Sen was found beside a clock that ran backward.',culprit:'Lucia',suspects:[{name:'Lucia',line:'I delivered a clock at ten and went straight home.'},{name:'Arman',line:'Sen was my mentor. I had no reason to hurt him.'},{name:'Tess',line:'I heard the chimes from across the square.'},{name:'Ravi',line:'I was fixing the tower mechanism all night.'}],evidence:['The backward clock hides a small remote receiver.','Lucia’s delivery van GPS stops transmitting beside the shop.','The thirteenth chime was a recording played through the tower speaker.','Sen had refused to sell Lucia a priceless pocket watch.','Packing straw from Lucia’s van is caught in the cellar latch.'],witnesses:['Ravi saw no one inside the tower mechanism.','A baker saw Lucia’s van return just before one.','Arman’s late-night call with Sen ended at 12:41.'],solution:'Lucia entered through the cellar, staged the recorded extra chime, and used the reversed clock to trigger the lights after she had gone.'}
]

const caseThreads:string[][]=[
  ['Kabir really did threaten Dev in front of six diners—but he left before the cake arrived.','The syrup on the packet and fork came from the same batch, narrowing the tampering window to nine minutes.','Meera washed every used fork except one. Why would a clean fork need hiding?'],
  ['Imran’s debt gives him motive, but his phone stayed connected to the downstairs printer.','The camera loop begins four seconds before the alarm: whoever made it knew the security routine.','Rain on the landing matters because the fire stairs are covered everywhere except the top step.'],
  ['The missing necklace looks like the motive, until the accounts reveal a much larger shortage.','The clock shift helps only someone whose alibi depends on the fireworks timestamp.','One veil pin was replaced with a safety pin after the group photograph.'],
  ['Jiya’s argument is genuine, but the dining-car receipt fixes her there at 1:08.','The station announcement proves the recorder—and the killer—were still aboard after the stop.','Tape fibres on the bolt match the adhesive caught inside Omar’s headphones.'],
  ['Diya publicly threatened Farah, making her an almost-too-perfect suspect.','The additive dries in twelve minutes; ordinary paint would still have been wet when the wall was found.','The disabled lift bought exactly enough time for a second coat.'],
  ['Aditya lied about why he took the boat, but the harbour beacon confirms where it travelled.','The splice is invisible at normal speed; headphones reveal a half-second room-tone change.','Only an administrator could schedule the smart speaker while everyone’s phones were offline.'],
  ['Nisha’s stolen research supplies a motive, yet her call recording shows no break in conversation.','The boot prints point away from the lodge, but only one set returns through the wood shed.','Fresh cedar inside a closed pocket could not have come from yesterday’s hike.'],
  ['Yusuf knew the booth better than anyone, but his old access card had been cancelled.','Purple varnish alone proves little; the copied-card timestamp and ladder witness make it useful.','The screen pulley was operated manually even though the projection controls were automated.'],
  ['Ben brought notes proving the cheating, but poison was placed before he entered the pub.','Changing the final answer guaranteed Ritesh—not the runner-up—would receive the cup.','The marker cap held poison without contaminating the question cards.'],
  ['Ravi could control the real chimes, which is exactly why the fake recording initially points at him.','The backward clock was not broken: its hands concealed the remote antenna.','Packing straw links the cellar route to a delivery that supposedly ended three hours earlier.']
]
const spriteStyle=(index:number)=>({backgroundPosition:`${(index%4)*100/3}% ${Math.floor(index/4)*50}%`})
const featuredEvidence=[0,1,2,3,4,5,6,7,8,9]
const suspectPortraits=[[1,0,3,2],[5,4,7,6],[9,8,10,11],[0,1,2,3],[4,5,6,7],[9,8,10,3],[0,1,5,2],[3,4,6,7],[9,8,10,11],[1,0,5,2]]

function Mystery({room}:{room:Room}){
  const localCase=room.gameEvents.filter(e=>e.type==='motive-case').at(-1)?.data as {index:number;session:string}|undefined
  const[selected,setSelected]=useState<number|null>(localCase?.index??null)
  const session=localCase?.session||''
  useEffect(()=>{if(localCase)setSelected(localCase.index)},[localCase?.session])
  if(selected===null)return <><section className="case-intro"><span>✦ CASEBOOK</span><h2>Ten mysteries. One room full of suspicious friends.</h2><p>Choose a file. Everyone gets the same evidence, statements and final vote.</p></section><div className="case-grid">{cases.map((c,i)=><button key={c.title} onClick={()=>{const s=crypto.randomUUID();room.sendGame('motive-case',{index:i,session:s});setSelected(i)}}><small>CASE {String(i+1).padStart(2,'0')}</small><b>{c.title}</b><span>{c.place}</span><em>Open file →</em></button>)}</div></>
  const c=cases[selected]
  const relevant=room.gameEvents.filter(e=>e.at>=(room.gameEvents.find(x=>x.type==='motive-case'&&(x.data as {session?:string}).session===session)?.at||0))
  const votes=Object.fromEntries(relevant.filter(e=>e.type==='motive-vote').map(e=>{const d=e.data as {player:string;suspect:string};return[d.player,d.suspect]}))
  const revealed=relevant.some(e=>e.type==='motive-reveal')
  return <div className="casebook"><button className="back" onClick={()=>setSelected(null)}>← All cases</button><section className="case-cover"><div><small>{c.place}</small><h2>{c.title}</h2><p><b>Victim:</b> {c.victim}</p><p>{c.hook}</p></div><div className="case-object"><div style={spriteStyle(featuredEvidence[selected])}/><small>FEATURED EVIDENCE</small></div></section><div className="file-columns"><section><h3>🔎 Evidence locker</h3>{c.evidence.map((x,i)=><article className="evidence" key={x}><b className="item-number">{String(i+1).padStart(2,'0')}</b><p><small>ITEM {i+1}</small>{x}</p></article>)}</section><section><h3>👁 Witness notes</h3>{c.witnesses.map((x,i)=><article className="witness-card" key={x}><div className="witness-photo" style={spriteStyle((selected*3+i+4)%12)}/><blockquote>“{x}”</blockquote></article>)}</section></div><section className="threads"><h3>🧵 Loose threads</h3><p>These details may clear a suspect, expose a lie—or send your table in completely the wrong direction.</p><div>{caseThreads[selected].map((x,i)=><article key={x}><b>0{i+1}</b><span>{x}</span></article>)}</div></section><h3>Statements from the accused</h3><div className="suspects">{c.suspects.map((s,i)=><article key={s.name}><div className="portrait" style={spriteStyle(suspectPortraits[selected][i])}/><b>{s.name}</b><p>“{s.line}”</p><button disabled={revealed} onClick={()=>room.sendGame('motive-vote',{player:room.id,suspect:s.name})}>{votes[room.id]===s.name?'Voted ✓':'Accuse'}</button></article>)}</div><section className={'verdict '+(revealed?'open':'')}><h3>{revealed?'THE TRUTH':'Seal your accusation'}</h3>{!revealed?<><p>{Object.keys(votes).length} vote(s) locked. Discuss the timeline, separate the lies from the red herrings, then reveal together.</p><button onClick={()=>room.sendGame('motive-reveal',{session})}>Reveal the murderer ✦</button></>:<><div className="reveal-name">{c.culprit.toUpperCase()}</div><p>{c.solution}</p><p className="vote-line">The room accused: {Object.values(votes).join(', ')||'nobody'}</p></>}</section></div>
}

type GuessState={session:string;players:Player[];stage:'choose-guesser'|'choose-secret'|'guessing'|'reveal';guesserVotes:Record<string,string>;guesserId?:string;secretVotes:Record<string,string>;secret?:string;duration?:number;deadline?:number;answer?:string;correct?:boolean;timedOut?:boolean}
function guessState(events:GameEvent[]):GuessState|null{return events.reduce<GuessState|null>((state,e)=>{if(e.type==='guess-start')return e.data as GuessState;if(!state)return null;if(e.type==='guess-vote-guesser'){const d=e.data as {player:string;target:string};return {...state,guesserVotes:{...state.guesserVotes,[d.player]:d.target}}}if(e.type==='guess-lock-guesser')return {...state,guesserId:(e.data as {guesserId:string}).guesserId,stage:'choose-secret',secretVotes:{}};if(e.type==='guess-secret'){const d=e.data as {player:string;secret:string};return {...state,secretVotes:{...state.secretVotes,[d.player]:d.secret}}}if(e.type==='guess-begin'){const d=e.data as {secret:string;duration:number;deadline:number};return {...state,...d,stage:'guessing'}}if(e.type==='guess-answer'){const answer=(e.data as {answer:string}).answer;return {...state,answer,correct:answer.trim().toLowerCase()===state.secret?.trim().toLowerCase(),stage:'reveal'}}if(e.type==='guess-timeout')return {...state,timedOut:true,correct:false,stage:'reveal'};return state},null)}
function Guess({room,me}:{room:Room;me:Player}){
  const s=guessState(room.gameEvents);const[secret,setSecret]=useState('');const[answer,setAnswer]=useState('');const[duration,setDuration]=useState(300);const[,tick]=useState(0);const timed=useRef<string[]>([])
  const players=useMemo(()=>[me,...room.peers.map(p=>({id:p.id,name:p.name}))].sort((a,b)=>a.id.localeCompare(b.id)),[me.id,me.name,room.peers])
  useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),250);return()=>clearInterval(timer)},[])
  const seconds=s?.stage==='guessing'&&s.deadline?Math.max(0,Math.ceil((s.deadline-Date.now())/1000)):0
  useEffect(()=>{if(!s||s.stage!=='guessing'||seconds>0||timed.current.includes(s.session))return;timed.current.push(s.session);room.sendGame('guess-timeout',{})},[seconds,s,room.sendGame])
  const name=(id?:string)=>s?.players.find(p=>p.id===id)?.name||players.find(p=>p.id===id)?.name||'friend'
  if(!s)return <section className="play"><span>?</span><h2>Guess the Person</h2><p>First, everyone votes for one friend to be the guesser. The rest secretly agree on a person, lock it, and start a 2, 5 or 10 minute question round.</p><p className="player-count">{players.length} player(s) in the room · minimum 2</p><button disabled={players.length<2} onClick={()=>room.sendGame('guess-start',{session:crypto.randomUUID(),players,stage:'choose-guesser',guesserVotes:{},secretVotes:{}} satisfies GuessState)}>Start a round</button></section>
  if(s.stage==='choose-guesser'){
    const counts:Record<string,number>={};Object.values(s.guesserVotes).forEach(v=>counts[v]=(counts[v]||0)+1);const max=Math.max(0,...Object.values(counts));const leaders=Object.keys(counts).filter(id=>counts[id]===max)
    return <section className="guess-board"><div className="guess-step">STEP 1 OF 3</div><h2>Who has to guess?</h2><p>Everyone votes. The choice locks only when everybody has voted and there is one clear winner.</p><div className="friend-ballot">{s.players.map(p=><button className={s.guesserVotes[me.id]===p.id?'chosen':''} key={p.id} onClick={()=>room.sendGame('guess-vote-guesser',{player:me.id,target:p.id})}><span>{p.name[0]}</span>{p.name}<small>{counts[p.id]||0} vote(s)</small></button>)}</div><p>{Object.keys(s.guesserVotes).length} / {s.players.length} votes in</p><button disabled={Object.keys(s.guesserVotes).length<s.players.length||leaders.length!==1} onClick={()=>room.sendGame('guess-lock-guesser',{guesserId:leaders[0]})}>Lock {name(leaders[0])} as guesser →</button></section>
  }
  if(s.stage==='choose-secret'){
    const voters=s.players.filter(p=>p.id!==s.guesserId);const locked=Object.keys(s.secretVotes).length;const answers=Object.values(s.secretVotes).map(x=>x.trim().toLowerCase()).filter(Boolean);const unanimous=answers.length===voters.length&&new Set(answers).size===1
    return <section className="guess-board"><div className="guess-step">STEP 2 OF 3 · SECRET SETUP</div><h2>{name(s.guesserId)} is the guesser</h2>{me.id===s.guesserId?<div className="blindfold"><span>🙈</span><h3>No peeking.</h3><p>Your friends are collectively locking the mystery person. You will see nothing until they are ready.</p></div>:<><p>Agree out loud, then every non-guesser must type the exact same person. The answer stays hidden from {name(s.guesserId)}.</p><form className="secret-form" onSubmit={e=>{e.preventDefault();if(secret.trim())room.sendGame('guess-secret',{player:me.id,secret:secret.trim()})}}><input value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Full name of the mystery person"/><button>{s.secretVotes[me.id]?'Update my lock':'Lock my choice'}</button></form><div className="duration-pick"><b>Question timer</b>{[120,300,600].map(n=><button className={duration===n?'chosen':''} key={n} onClick={()=>setDuration(n)}>{n/60} min</button>)}</div></>}<p className="lock-status">🔒 {locked} / {voters.length} friends locked {unanimous?'· unanimous ✓':''}</p>{me.id!==s.guesserId&&<button disabled={!unanimous} onClick={()=>room.sendGame('guess-begin',{secret:Object.values(s.secretVotes)[0],duration,deadline:Date.now()+duration*1000})}>Seal answer & start timer →</button>}</section>
  }
  if(s.stage==='guessing')return <section className="guess-board live-guess"><div className="guess-clock"><small>TIME LEFT</small><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><i style={{width:`${seconds/(s.duration||1)*100}%`}}/></div><h2>{name(s.guesserId)} is asking questions</h2><p>Ask as many yes-or-no questions as you want. Friends: answer honestly, but do not say the name.</p>{me.id===s.guesserId?<form className="final-guess" onSubmit={e=>{e.preventDefault();if(answer.trim())room.sendGame('guess-answer',{answer:answer.trim()})}}><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="I think the person is…"/><button>Lock final answer</button></form>:<div className="blindfold"><span>🤫</span><h3>Keep the secret.</h3><p>{name(s.guesserId)} must lock an answer before the clock reaches zero.</p></div>}</section>
  return <section className={'guess-reveal '+(s.correct?'win':'lose')}><span>{s.correct?'🎉':'⏰'}</span><small>THE PERSON WAS</small><h2>{s.secret}</h2>{s.timedOut?<p>{name(s.guesserId)} ran out of time before locking an answer.</p>:<p>{name(s.guesserId)} guessed <b>{s.answer}</b> — {s.correct?'exactly right!':'not quite.'}</p>}<button onClick={()=>room.sendGame('guess-start',{session:crypto.randomUUID(),players,stage:'choose-guesser',guesserVotes:{},secretVotes:{}} satisfies GuessState)}>Play another round</button></section>
}

type MafiaState={session:string;players:Player[];roles:Record<string,'mafia'|'doctor'|'civilian'>;alive:string[];stage:'mafia'|'doctor'|'vote'|'ended';round:number;kill?:string;save?:string;dead?:string;votes:Record<string,string>;winner?:'mafia'|'civilians'}
function mafiaState(events:GameEvent[]):MafiaState|null{return events.reduce<MafiaState|null>((state,e)=>{if(e.type==='mafia-start')return e.data as MafiaState;if(!state)return null;if(e.type==='mafia-kill')return {...state,kill:(e.data as {target:string}).target,stage:'doctor'};if(e.type==='mafia-save'){const save=(e.data as {target?:string}).target;const dead:string|undefined=state.kill!==save?state.kill:undefined;const alive:string[]=dead?state.alive.filter(id=>id!==dead):state.alive;const mafia:string=Object.keys(state.roles).find(id=>state.roles[id]==='mafia')||'';const mafiaWins=alive.includes(mafia)&&alive.filter(id=>id!==mafia).length<=1;return {...state,save,dead,alive,stage:mafiaWins?'ended':'vote',winner:mafiaWins?'mafia':undefined,votes:{}}}if(e.type==='mafia-vote'){const d=e.data as {player:string;target:string};return {...state,votes:{...state.votes,[d.player]:d.target}}}if(e.type==='mafia-end')return {...state,stage:'ended',winner:(e.data as {winner:'mafia'|'civilians'}).winner};if(e.type==='mafia-next')return {...state,round:state.round+1,stage:'mafia',kill:undefined,save:undefined,dead:undefined,votes:{}};return state},null)}
function Mafia({room,me}:{room:Room;me:Player}){
  const s=mafiaState(room.gameEvents)
  const players=useMemo(()=>[me,...room.peers.map(p=>({id:p.id,name:p.name}))].sort((a,b)=>a.id.localeCompare(b.id)),[me.id,me.name,room.peers])
  if(!s)return <section className="play"><span>☾</span><h2>Mafia & Doctor</h2><p>The computer privately assigns one Mafia, one Doctor and the rest Civilians. Night choices stay hidden until the result.</p><p className="player-count">{players.length} player(s) in the room · minimum 3</p><button disabled={!room.isHost||players.length<3} onClick={()=>{const shuffled=[...players].sort(()=>Math.random()-.5);const roles:Record<string,'mafia'|'doctor'|'civilian'>={};players.forEach(p=>roles[p.id]='civilian');roles[shuffled[0].id]='mafia';roles[shuffled[1].id]='doctor';room.sendGame('mafia-start',{session:crypto.randomUUID(),players,roles,alive:players.map(p=>p.id),stage:'mafia',round:1,votes:{}} satisfies MafiaState)}}>{room.isHost?'Start and deal roles':'Waiting for host'}</button></section>
  const role=s.roles[me.id];const alive=s.alive.includes(me.id);const name=(id?:string)=>s.players.find(p=>p.id===id)?.name||'Nobody';const targets=s.players.filter(p=>s.alive.includes(p.id)&&p.id!==me.id)
  const finalize=()=>{const counts:Record<string,number>={};Object.values(s.votes).forEach(v=>counts[v]=(counts[v]||0)+1);const mafia=Object.keys(s.roles).find(x=>s.roles[x]==='mafia')!;const max=Math.max(0,...Object.values(counts));const leaders=Object.keys(counts).filter(x=>counts[x]===max);room.sendGame(leaders.length===1&&leaders[0]===mafia?'mafia-end':'mafia-next',leaders.length===1&&leaders[0]===mafia?{winner:'civilians'}:{})}
  return <section className="mafia-board"><div className={'role-card '+role}><small>YOUR SECRET ROLE</small><h2>{role?.toUpperCase()||'SPECTATOR'}</h2><p>{role==='mafia'?'Choose one player to eliminate each night. Survive every vote.':role==='doctor'?'Choose one player to protect after the Mafia moves.':'Discuss the result and vote out the Mafia.'}</p></div><div className="round-head"><b>ROUND {s.round}</b><span>{s.alive.length} alive</span></div>{!alive&&s.stage!=='ended'&&<p className="dead-note">You are out. Watch quietly—your role remains secret.</p>}
  {s.stage==='mafia'&&<section className="night"><h3>🌙 The Mafia is choosing…</h3>{role==='mafia'&&alive?<div className="target-grid">{targets.map(p=><button key={p.id} onClick={()=>room.sendGame('mafia-kill',{target:p.id})}>Kill {p.name}</button>)}</div>:<p>Your screen stays dark while the Mafia decides.</p>}</section>}
  {s.stage==='doctor'&&<section className="night doctor-night"><h3>🩺 The Doctor is choosing…</h3>{role==='doctor'&&alive?<div className="target-grid">{s.players.filter(p=>s.alive.includes(p.id)).map(p=><button key={p.id} onClick={()=>room.sendGame('mafia-save',{target:p.id})}>Save {p.name}</button>)}</div>:<p>The Mafia has locked a target. Only the Doctor can act now.</p>}{room.isHost&&!s.alive.some(id=>s.roles[id]==='doctor')&&<button onClick={()=>room.sendGame('mafia-save',{})}>Continue — the Doctor is out</button>}</section>}
  {s.stage==='vote'&&<section className="day"><h3>{s.dead?`💀 ${name(s.dead)} was killed.`:'✨ The Doctor made the save. Nobody died.'}</h3><p>Talk it out. Then every living player votes once.</p>{alive&&<div className="target-grid">{targets.map(p=><button className={s.votes[me.id]===p.id?'chosen':''} key={p.id} onClick={()=>room.sendGame('mafia-vote',{player:me.id,target:p.id})}>{s.votes[me.id]===p.id?'✓ ':''}{p.name}</button>)}</div>}<p>{Object.keys(s.votes).length} / {s.alive.length} votes locked</p>{room.isHost&&<button disabled={Object.keys(s.votes).length<s.alive.length} onClick={finalize}>Count the votes →</button>}</section>}
  {s.stage==='ended'&&<section className="game-over"><span>{s.winner==='mafia'?'☾':'✦'}</span><h2>{s.winner==='mafia'?'THE MAFIA WINS':'THE MAFIA WAS CAUGHT'}</h2><p>The Mafia was <b>{name(Object.keys(s.roles).find(x=>s.roles[x]==='mafia'))}</b>. The Doctor was <b>{name(Object.keys(s.roles).find(x=>s.roles[x]==='doctor'))}</b>.</p></section>}</section>
}

type PachState={session:string;players:Player[];targets:Record<string,number>;active:string[];total:number;round:number;deadline:number;phase:'raising'|'reveal'|'ended';choices:Record<string,number>;gain?:number;safeId?:string}
function pachState(events:GameEvent[]):PachState|null{return events.reduce<PachState|null>((state,e)=>{if(e.type==='pach-start')return e.data as PachState;if(!state)return null;if(e.type==='pach-pick'){const d=e.data as {player:string;raise:number;round:number};return d.round===state.round?{...state,choices:{...state.choices,[d.player]:d.raise}}:state}if(e.type==='pach-reveal'){const d=e.data as {round:number;gain:number;total:number;safeId?:string;active:string[]};return d.round===state.round?{...state,...d,phase:d.active.length<=1?'ended':'reveal'}:state}if(e.type==='pach-next')return {...state,round:state.round+1,deadline:(e.data as {deadline:number}).deadline,phase:'raising',choices:{},gain:undefined,safeId:undefined};return state},null)}
function Pacheesa({room,me}:{room:Room;me:Player}){
  const s=pachState(room.gameEvents);const[,tick]=useState(0);const resolved=useRef<number[]>([])
  const players=useMemo(()=>[me,...room.peers.map(p=>({id:p.id,name:p.name}))].sort((a,b)=>a.id.localeCompare(b.id)),[me.id,me.name,room.peers])
  useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),250);return()=>clearInterval(timer)},[])
  const seconds=s?.phase==='raising'?Math.max(0,Math.ceil((s.deadline-Date.now())/1000)):0
  useEffect(()=>{if(!s||!room.isHost||s.phase!=='raising'||Date.now()<s.deadline||resolved.current.includes(s.round))return;resolved.current.push(s.round);const gain=Object.values(s.choices).reduce((a,b)=>a+b,0);const next=s.total+gain;const safeId=s.active.find(id=>s.targets[id]===next);room.sendGame('pach-reveal',{round:s.round,gain,total:safeId?0:next,safeId,active:safeId?s.active.filter(id=>id!==safeId):s.active})},[seconds,s,room.isHost,room.sendGame])
  if(!s)return <section className="play"><span>5</span><h2>Pacheesa</h2><p>Each player gets a unique multiple of 5. You have 15 seconds to secretly raise 0, 5 or 10. Nobody sees anyone’s choice until time runs out.</p><p className="player-count">{players.length} player(s) in the room · minimum 2</p><button disabled={!room.isHost||players.length<2} onClick={()=>{const nums=Array.from({length:players.length*2},(_,i)=>(i+1)*5).sort(()=>Math.random()-.5).slice(0,players.length);const targets=Object.fromEntries(players.map((p,i)=>[p.id,nums[i]]));room.sendGame('pach-start',{session:crypto.randomUUID(),players,targets,active:players.map(p=>p.id),total:0,round:1,deadline:Date.now()+15000,phase:'raising',choices:{}} satisfies PachState)}}>{room.isHost?'Start Pacheesa':'Waiting for host'}</button></section>
  const mine=s.choices[me.id];const myActive=s.active.includes(me.id);const name=(id?:string)=>s.players.find(p=>p.id===id)?.name||''
  return <section className="pacheesa"><div className="pach-title"><span>5</span><div><h2>Pacheesa</h2><p>Round {s.round} · Hit a target and that player becomes safe. The running total then returns to 0.</p></div></div><div className="score-strip"><div><small>RUNNING TOTAL</small><b>{s.total}</b></div><div><small>YOUR NUMBER</small><b>{s.targets[me.id]??'—'}</b></div><div className={seconds<=5?'urgent':''}><small>SECRET TIMER</small><b>{s.phase==='raising'?seconds+'s':'—'}</b></div></div><div className="target-list">{s.players.map(p=><span className={!s.active.includes(p.id)?'safe-player':''} key={p.id}>{!s.active.includes(p.id)?'✓ ':''}{p.name} · {s.targets[p.id]}</span>)}</div>
  {s.phase==='raising'&&<section className="secret-pick"><h3>{myActive?'Choose your raise':'You are safe—watch this round.'}</h3>{myActive&&<div className="raise-buttons">{[0,5,10].map(n=><button className={mine===n?'chosen':''} key={n} onClick={()=>room.sendGame('pach-pick',{player:me.id,raise:n,round:s.round})}>+{n}</button>)}</div>}<p>{mine!==undefined?'Your choice is locked. You can change it until time runs out.':'Unchosen players count as +0.'}</p><div className="timer-bar"><i style={{width:`${seconds/15*100}%`}}/></div></section>}
  {s.phase==='reveal'&&<section className="turn-reveal"><small>THE ROOM RAISED</small><strong>+{s.gain}</strong>{s.safeId?<h3>🎉 {name(s.safeId)} hit {s.targets[s.safeId]} and is safe! Total reset to 0.</h3>:<h3>No target hit. The total carries forward.</h3>}{room.isHost&&<button onClick={()=>room.sendGame('pach-next',{deadline:Date.now()+15000})}>Start next 15 seconds →</button>}</section>}
  {s.phase==='ended'&&<section className="game-over"><span>✦</span><h2>{name(s.active[0])} is the last player standing</h2><p>Everyone else made it safely out. The total finished at {s.total}.</p></section>}</section>
}
