import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { GameEvent,Peer } from './game/useRoom'
import { supabase } from './supabaseClient'

type Player={id:string;name:string}
type Shot={playerId:string;name:string;url:string}
type Booth={id:string;hostId:string;hostName:string;invited:Player[];accepted:Record<string,boolean>;prompt:string;effect:Effect;status:'lobby'|'countdown'|'review'|'done';deadline?:number;shots:Record<string,Shot>;finalUrl?:string}
type Effect='clean'|'retro'|'digicam'|'mono'|'dreamy'
type GalleryPhoto={id:string;image_url:string;prompt:string;effect:string;participants:string[];created_at:string}
const prompts=['album cover energy','pretend you just heard the wildest tea','awkward family portrait','caught laughing mid-sentence','everyone look in a different direction','tiny sunglasses, huge confidence','yearbook photo from another universe','the group chat became real','soft smiles only','main characters at 2 a.m.']
const effects:Array<[Effect,string,string]>=[['clean','Clean','soft & true'],['retro','Retro','warm film fade'],['digicam','Digicam','flashy 2000s'],['mono','B&W','classic grain'],['dreamy','Dreamy','pastel glow']]
const filters:Record<Effect,string>={clean:'none',retro:'sepia(.35) contrast(1.12) saturate(.82) brightness(1.04)',digicam:'contrast(1.18) saturate(1.28) brightness(1.07)',mono:'grayscale(1) contrast(1.15)',dreamy:'brightness(1.1) saturate(.82) contrast(.92)'}

function boothState(events:GameEvent[]):Booth|null{return events.reduce<Booth|null>((state,e)=>{if(e.type==='booth-start')return e.data as Booth;if(!state)return null;const d=e.data as Record<string,unknown>;if(d.session!==state.id)return state;if(e.type==='booth-response')return {...state,accepted:{...state.accepted,[String(d.playerId)]:Boolean(d.accepted)}};if(e.type==='booth-launch')return {...state,status:'countdown',deadline:Number(d.deadline)};if(e.type==='booth-shot'){const shot=d.shot as Shot;const shots={...state.shots,[shot.playerId]:shot};const expected=[state.hostId,...state.invited.filter(p=>state.accepted[p.id]).map(p=>p.id)];return {...state,status:expected.every(id=>shots[id])?'review':state.status,shots}}if(e.type==='booth-final')return {...state,status:'done',finalUrl:String(d.url)};return state},null)}

export default function PhotoBooth({roomCode,userId,name,peers,gameEvents,sendGame}:{roomCode:string;userId:string;name:string;peers:Peer[];gameEvents:GameEvent[];sendGame:(type:string,data:unknown)=>void}){
  const booth=boothState(gameEvents);const[selected,setSelected]=useState<string[]>([]);const[prompt,setPrompt]=useState(prompts[0]);const[effect,setEffect]=useState<Effect>('retro');const[gallery,setGallery]=useState<GalleryPhoto[]>([]);const[error,setError]=useState('');const[cameraError,setCameraError]=useState('');const[cameraReady,setCameraReady]=useState(false);const[requestingCamera,setRequestingCamera]=useState(false);const[composing,setComposing]=useState(false);const[,tick]=useState(0)
  const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const captured=useRef<string[]>([])
  const loadGallery=useCallback(async()=>{if(!supabase)return;const{data,error:e}=await supabase.from('lounge_photos').select('*').eq('room_code',roomCode).order('created_at',{ascending:false}).limit(24);if(e)setError(e.message);else setGallery((data||[]) as GalleryPhoto[])},[roomCode])
  useEffect(()=>{void loadGallery();const client=supabase;if(!client)return;const channel=client.channel(`photo-gallery:${roomCode}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'lounge_photos',filter:`room_code=eq.${roomCode}`},()=>void loadGallery()).subscribe();return()=>{void client.removeChannel(channel)}},[loadGallery,roomCode])
  const isInvited=Boolean(booth?.invited.some(p=>p.id===userId));const accepted=booth?.hostId===userId||booth?.accepted[userId]===true;const involved=booth?.hostId===userId||isInvited
  const startCamera=useCallback(async()=>{if(!navigator.mediaDevices?.getUserMedia){setCameraError(location.protocol==='https:'?'This browser does not provide camera access. Try a current version of Chrome, Edge or Safari.':'Camera access only works on HTTPS or localhost.');return}setRequestingCamera(true);setCameraError('');setCameraReady(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;let lastError:unknown;for(const constraints of [{video:{facingMode:'user'},audio:false},{video:true,audio:false}]){try{const next=await navigator.mediaDevices.getUserMedia(constraints);stream.current=next;if(video.current){video.current.srcObject=next;await video.current.play()}setCameraReady(true);setRequestingCamera(false);return}catch(e){lastError=e;if(e instanceof DOMException&&!['OverconstrainedError','AbortError'].includes(e.name))break}}const name=lastError instanceof DOMException?lastError.name:'';const messages:Record<string,string>={NotAllowedError:'Camera access is blocked for this site. Open the lock/camera icon in the address bar, allow access, then press Retry camera.',NotReadableError:'Permission is allowed, but the camera is busy. Close Camera, Zoom, Teams, or another browser tab and retry.',NotFoundError:'No usable camera was found on this device.',SecurityError:'The browser blocked camera access. Open the lounge over HTTPS and retry.',AbortError:'Camera startup was interrupted. Wait a moment and retry.',OverconstrainedError:'The selected camera could not satisfy the requested settings. Retry will use basic settings.'};setCameraError(messages[name]||`The camera could not start${name?` (${name})`:''}. Try closing other camera apps and retry.`);setRequestingCamera(false)},[])
  useEffect(()=>{if(!booth||!accepted||!['lobby','countdown','review'].includes(booth.status)){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCameraReady(false);return}void startCamera();return()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[booth?.id,accepted,startCamera])
  useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),200);return()=>clearInterval(timer)},[])
  const seconds=booth?.status==='countdown'&&booth.deadline?Math.max(0,Math.ceil((booth.deadline-Date.now())/1000)):0
  const uploadFrame=useCallback(async()=>{if(!booth||!video.current||!supabase||captured.current.includes(booth.id))return;captured.current.push(booth.id);const canvas=document.createElement('canvas');canvas.width=960;canvas.height=720;const ctx=canvas.getContext('2d')!;ctx.filter=filters[booth.effect];ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(video.current,0,0,canvas.width,canvas.height);ctx.setTransform(1,0,0,1,0,0);ctx.filter='none';if(booth.effect==='digicam'){ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='white';ctx.font='22px monospace';ctx.fillText(new Date().toLocaleDateString(),25,690)}const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob){captured.current=captured.current.filter(id=>id!==booth.id);setError('Could not capture the frame.');return}const path=`${roomCode}/${booth.id}/${userId}.jpg`;const up=await supabase.storage.from('lounge-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(up.error){captured.current=captured.current.filter(id=>id!==booth.id);setError(up.error.message);return}const{data}=supabase.storage.from('lounge-photos').getPublicUrl(path);sendGame('booth-shot',{session:booth.id,shot:{playerId:userId,name,url:data.publicUrl}})},[booth,roomCode,userId,name,sendGame])
  useEffect(()=>{if(booth?.status==='countdown'&&seconds===0&&cameraReady)void uploadFrame()},[booth?.status,seconds,cameraReady,uploadFrame])
  const participants=useMemo(()=>booth?[{id:booth.hostId,name:booth.hostName},...booth.invited.filter(p=>booth.accepted[p.id])]:[],[booth])
  const allResponded=booth?booth.invited.every(p=>booth.accepted[p.id]!==undefined):false;const allShot=booth?participants.every(p=>booth.shots[p.id]):false
  const compose=async()=>{if(!booth||!supabase||!allShot)return;setComposing(true);try{const shots=participants.map(p=>booth.shots[p.id]);const images=await Promise.all(shots.map(s=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=s.url})));const cols=images.length===1?1:images.length<=4?2:3;const rows=Math.ceil(images.length/cols);const width=1200,cellW=width/cols,cellH=520,height=rows*cellH+190;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff4df';ctx.fillRect(0,0,width,height);images.forEach((img,i)=>{const x=i%cols*cellW,y=Math.floor(i/cols)*cellH;ctx.save();ctx.beginPath();ctx.rect(x+18,y+18,cellW-36,cellH-58);ctx.clip();const scale=Math.max((cellW-36)/img.width,(cellH-58)/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,x+(cellW-w)/2,y+18+(cellH-58-h)/2,w,h);ctx.restore();ctx.fillStyle='#403b56';ctx.font='700 24px sans-serif';ctx.fillText(shots[i].name,x+25,y+cellH-14)});ctx.fillStyle='#4e4a75';ctx.fillRect(0,height-190,width,190);ctx.fillStyle='#ffc777';ctx.font='700 26px sans-serif';ctx.fillText('THE COMMON LOUNGE PHOTOBOOTH',45,height-132);ctx.fillStyle='white';ctx.font='italic 42px serif';ctx.fillText(`“${booth.prompt}”`,45,height-72);ctx.font='20px sans-serif';ctx.fillText(new Date().toLocaleString(),45,height-32);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw new Error('Could not compose photo.');const path=`${roomCode}/gallery/${booth.id}.jpg`;const up=await supabase.storage.from('lounge-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(up.error)throw up.error;const{data}=supabase.storage.from('lounge-photos').getPublicUrl(path);const saved=await supabase.from('lounge_photos').upsert({room_code:roomCode,session_id:booth.id,image_url:data.publicUrl,prompt:booth.prompt,effect:booth.effect,participants:participants.map(p=>p.name)},{onConflict:'session_id'});if(saved.error)throw saved.error;sendGame('booth-final',{session:booth.id,url:data.publicUrl});await loadGallery()}catch(e){setError(e instanceof Error?e.message:'Could not compose the group photo.')}finally{setComposing(false)}}
  const start=()=>{const invitees=peers.filter(p=>selected.includes(p.id)).map(p=>({id:p.id,name:p.name}));const id=crypto.randomUUID();sendGame('booth-start',{id,hostId:userId,hostName:name,invited:invitees,accepted:{[userId]:true},prompt,effect,status:'lobby',shots:{}} satisfies Booth)}
  return <div className="booth"><section className="booth-hero"><div><small>📸 THE REMOTE PHOTOBOOTH</small><h2>Different rooms.<br/>Same photograph.</h2><p>Invite online friends, strike the same prompt, and the booth brings every frame together.</p></div><div className="film-strip"><i/><i/><i/></div></section>{error&&<p className="data-error">{error}</p>}
  {!booth&&<section className="booth-setup"><h3>Set the vibe</h3><label>Prompt<select value={prompt} onChange={e=>setPrompt(e.target.value)}>{prompts.map(p=><option key={p}>{p}</option>)}</select></label><div className="effect-grid">{effects.map(([id,title,sub])=><button className={effect===id?'chosen':''} key={id} onClick={()=>setEffect(id)}><span className={'effect-preview '+id}/><b>{title}</b><small>{sub}</small></button>)}</div><h3>Who is in this one?</h3><div className="online-invites">{peers.length===0?<p>Nobody else is online—take a solo picture or share the room link.</p>:peers.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/><span>{p.name[0]}</span>{p.name}</label>)}</div><button className="booth-primary" onClick={start}>{selected.length?`Invite ${selected.length} friend${selected.length>1?'s':''}`:'Take a solo photo'} →</button></section>}
  {booth&&isInvited&&booth.accepted[userId]===undefined&&<section className="booth-invite"><span>📷</span><h2>{booth.hostName} invited you to a photo</h2><p>Prompt: “{booth.prompt}” · {booth.effect} effect</p><button onClick={()=>sendGame('booth-response',{session:booth.id,playerId:userId,accepted:true})}>Join the picture</button><button className="ghost" onClick={()=>sendGame('booth-response',{session:booth.id,playerId:userId,accepted:false})}>Not this one</button></section>}
  {booth&&!involved&&<section className="booth-wait"><h3>A private booth session is in progress</h3><p>{booth.hostName} invited selected friends. The gallery is still open below.</p></section>}
  {booth&&accepted&&booth.status!=='done'&&<section className="camera-stage"><div className={'camera-view '+booth.effect}><video ref={video} autoPlay muted playsInline/><div className="viewfinder"/><span className="camera-prompt">{booth.prompt}</span>{!cameraReady&&!requestingCamera&&<button className="camera-enable" onClick={()=>void startCamera()}>Enable camera</button>}{requestingCamera&&<strong className="camera-loading">Starting camera…</strong>}{booth.status==='countdown'&&<strong className="camera-count">{seconds||'CLICK!'}</strong>}</div><div className="session-panel"><small>SESSION BY {booth.hostName.toUpperCase()}</small><h3>{booth.status==='lobby'?'Friends are joining…':booth.status==='countdown'?'Hold that pose!':'Frames received'}</h3>{cameraError&&<div className="camera-error"><p>{cameraError}</p><button onClick={()=>void startCamera()}>Retry camera</button></div>}{cameraReady&&<p className="camera-ok">● Camera ready</p>}<div className="participant-list">{[{id:booth.hostId,name:booth.hostName},...booth.invited].map(p=><span key={p.id}>{booth.shots[p.id]?'✓':booth.accepted[p.id]===false?'×':booth.accepted[p.id]?'●':'○'} {p.name}</span>)}</div>{booth.hostId===userId&&booth.status==='lobby'&&<button className="booth-primary" disabled={!allResponded||!cameraReady} onClick={()=>sendGame('booth-launch',{session:booth.id,deadline:Date.now()+4000})}>Start 3-second countdown</button>}{booth.status==='countdown'&&seconds===0&&!booth.shots[userId]&&<button className="booth-primary" disabled={!cameraReady} onClick={()=>void uploadFrame()}>Retry my capture</button>}{booth.hostId===userId&&booth.status==='review'&&<button className="booth-primary" disabled={!allShot||composing} onClick={()=>void compose()}>{composing?'Developing…':'Develop group photo ✦'}</button>}{booth.status==='countdown'&&seconds===0&&!allShot&&<p>Waiting for every camera to send its frame…</p>}</div></section>}
  {booth?.status==='done'&&involved&&<section className="booth-result"><small>FRESH FROM THE DARKROOM</small><img src={booth.finalUrl} alt={`Photobooth: ${booth.prompt}`}/><div><a href={booth.finalUrl} download target="_blank" rel="noreferrer">Download photo</a><button onClick={()=>sendGame('booth-start',{id:crypto.randomUUID(),hostId:userId,hostName:name,invited:[],accepted:{[userId]:true},prompt:prompts[0],effect:'retro',status:'lobby',shots:{}} satisfies Booth)}>New photo</button></div></section>}
  <section className="gallery"><div><small>ROOM {roomCode}</small><h2>Shared photo drawer</h2><p>Saved on the web for everyone with this room.</p></div>{gallery.length===0?<p className="empty-gallery">Your first developed photo will appear here.</p>:<div className="gallery-grid">{gallery.map(photo=><figure key={photo.id}><img src={photo.image_url} alt={photo.prompt}/><figcaption><b>{photo.prompt}</b><span>{photo.participants.join(' · ')}</span></figcaption></figure>)}</div>}</section></div>
}
