import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { GameEvent,Peer } from './game/useRoom'
import { supabase } from './supabaseClient'

type Player={id:string;name:string}
type Shot={playerId:string;name:string;url:string}
type Effect='clean'|'retro'|'digicam'|'disposable'|'mono'|'dreamy'|'candy'
type Wallpaper='diner'|'clouds'|'scrapbook'|'disco'|'midnight'|'candywave'
type Prop='none'|'crown'|'glasses'|'cowgirl'|'cat'|'bows'|'hearts'|'wings'|'stars'
type Booth={id:string;hostId:string;hostName:string;invited:Player[];accepted:Record<string,boolean>;prompt:string;effect:Effect;wallpaper:Wallpaper;prop:Prop;status:'lobby'|'countdown'|'review'|'done';deadline?:number;shots:Record<string,Shot>;finalUrl?:string}
type GalleryPhoto={id:string;image_url:string;prompt:string;effect:string;participants:string[];created_at:string}

const prompts=['album cover energy','pretend you just heard the wildest tea','awkward family portrait','caught laughing mid-sentence','everyone look in a different direction','tiny sunglasses, huge confidence','yearbook photo from another universe','the group chat became real','soft smiles only','main characters at 2 a.m.','we definitely planned these outfits','caught by the paparazzi at brunch','one serious face, everyone else chaotic','rom-com poster but nobody knows the plot']
const effects:Array<[Effect,string,string]>=[['clean','Soft flash','glowy & true'],['retro','Retro film','leaks + dust'],['digicam','Digicam','Y2K flash + date'],['disposable','Disposable','grainy party cam'],['mono','Photo booth B&W','high contrast strip'],['dreamy','Dream haze','pastel bloom'],['candy','Candy flash','pink-blue pop']]
const wallpapers:Array<[Wallpaper,string]>=[['diner','Pink diner'],['clouds','Moon clouds'],['scrapbook','Flower scrapbook'],['disco','Disco tinsel'],['midnight','Midnight bedroom'],['candywave','Candy waves']]
const props:Array<[Prop,string]>=[['none','No prop'],['crown','Star crown'],['glasses','Pixel shades'],['cowgirl','Pink cowgirl'],['cat','Bow cat ears'],['bows','Gingham bows'],['hearts','Heart halo'],['wings','Angel wings'],['stars','Disco stars']]
const filters:Record<Effect,string>={clean:'brightness(1.06) saturate(1.04)',retro:'sepia(.38) contrast(1.14) saturate(.78) brightness(1.02)',digicam:'contrast(1.22) saturate(1.32) brightness(1.12)',disposable:'sepia(.12) contrast(1.25) saturate(1.05)',mono:'grayscale(1) contrast(1.32)',dreamy:'brightness(1.13) saturate(.78) contrast(.9)',candy:'contrast(1.1) saturate(1.48) hue-rotate(-5deg)'}
const wallpaperOrder:Wallpaper[]=['diner','clouds','scrapbook','disco','midnight','candywave']
const propOrder:Exclude<Prop,'none'>[]=['crown','glasses','cowgirl','cat','bows','hearts','wings','stars']

function boothState(events:GameEvent[]):Booth|null{return events.reduce<Booth|null>((state,e)=>{if(e.type==='booth-start')return e.data as Booth;if(!state)return null;const d=e.data as Record<string,unknown>;if(d.session!==state.id)return state;if(e.type==='booth-response')return {...state,accepted:{...state.accepted,[String(d.playerId)]:Boolean(d.accepted)}};if(e.type==='booth-launch')return {...state,status:'countdown',deadline:Number(d.deadline)};if(e.type==='booth-shot'){const shot=d.shot as Shot;const shots={...state.shots,[shot.playerId]:shot};const expected=[state.hostId,...state.invited.filter(p=>state.accepted[p.id]).map(p=>p.id)];return {...state,status:expected.every(id=>shots[id])?'review':state.status,shots}}if(e.type==='booth-final')return {...state,status:'done',finalUrl:String(d.url)};return state},null)}
const loadImage=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=reject;image.src=src})
function wallpaperPosition(id:Wallpaper){const i=wallpaperOrder.indexOf(id);return `${(i%3)*50}% ${Math.floor(i/3)*100}%`}
function propPosition(id:Prop){if(id==='none')return '0 0';const i=propOrder.indexOf(id);return `${(i%4)*100/3}% ${Math.floor(i/4)*100}%`}
function drawWallpaper(ctx:CanvasRenderingContext2D,image:HTMLImageElement,id:Wallpaper,x:number,y:number,w:number,h:number){const i=wallpaperOrder.indexOf(id),sw=image.width/3,sh=image.height/2;ctx.drawImage(image,(i%3)*sw,Math.floor(i/3)*sh,sw,sh,x,y,w,h)}
function drawProp(ctx:CanvasRenderingContext2D,image:HTMLImageElement,id:Prop,width:number,height:number){if(id==='none')return;const i=propOrder.indexOf(id),sw=image.width/4,sh=image.height/2,sx=(i%4)*sw,sy=Math.floor(i/4)*sh;const positions:Record<Exclude<Prop,'none'>,[number,number,number,number]>={crown:[.29,-.01,.42,.4],glasses:[.27,.24,.46,.36],cowgirl:[.2,-.02,.6,.42],cat:[.28,-.01,.44,.4],bows:[.16,.02,.68,.4],hearts:[.2,-.03,.6,.43],wings:[.06,.13,.88,.7],stars:[.1,.02,.8,.62]};const[x,y,w,h]=positions[id];ctx.drawImage(image,sx,sy,sw,sh,x*width,y*height,w*width,h*height)}
function addGrain(ctx:CanvasRenderingContext2D,w:number,h:number,amount=.13){ctx.save();for(let i=0;i<900;i++){const a=Math.random()*amount;ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.fillRect(Math.random()*w,Math.random()*h,Math.random()*2+1,Math.random()*2+1)}ctx.restore()}
function decorate(ctx:CanvasRenderingContext2D,effect:Effect,w:number,h:number){ctx.save();if(effect==='retro'){const leak=ctx.createRadialGradient(w*.05,h*.45,0,w*.05,h*.45,w*.55);leak.addColorStop(0,'rgba(255,72,35,.52)');leak.addColorStop(1,'rgba(255,170,70,0)');ctx.fillStyle=leak;ctx.fillRect(0,0,w,h);addGrain(ctx,w,h,.18);ctx.strokeStyle='rgba(255,248,220,.75)';ctx.lineWidth=13;ctx.strokeRect(25,25,w-50,h-50);ctx.fillStyle='#ffe7a4';ctx.font='18px monospace';ctx.fillText('FILM 24  •  1998',55,h-48)}if(effect==='digicam'){const flash=ctx.createRadialGradient(w*.52,h*.32,0,w*.52,h*.32,w*.65);flash.addColorStop(0,'rgba(255,255,255,.24)');flash.addColorStop(1,'rgba(190,220,255,0)');ctx.fillStyle=flash;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(8,15,38,.26)';ctx.fillRect(0,0,w,35);ctx.fillStyle='#ffec80';ctx.font='bold 18px monospace';ctx.fillText('AUTO  ✦  00:00',28,24);ctx.fillStyle='white';ctx.font='22px monospace';ctx.fillText(new Date().toLocaleDateString(),28,h-28);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=2;ctx.strokeRect(18,18,w-36,h-36)}if(effect==='disposable'){const leak=ctx.createLinearGradient(0,0,w,h);leak.addColorStop(0,'rgba(255,200,60,.28)');leak.addColorStop(.55,'rgba(255,255,255,0)');leak.addColorStop(1,'rgba(230,65,60,.25)');ctx.fillStyle=leak;ctx.fillRect(0,0,w,h);addGrain(ctx,w,h,.24);ctx.strokeStyle='#fff7e9';ctx.lineWidth=28;ctx.strokeRect(14,14,w-28,h-28)}if(effect==='mono'){addGrain(ctx,w,h,.2);ctx.strokeStyle='white';ctx.lineWidth=18;ctx.strokeRect(18,18,w-36,h-36);ctx.fillStyle='white';ctx.font='bold 18px monospace';ctx.fillText('B&W • 400',35,h-35)}if(effect==='dreamy'){const haze=ctx.createLinearGradient(0,0,w,h);haze.addColorStop(0,'rgba(255,170,225,.28)');haze.addColorStop(.5,'rgba(255,255,255,.05)');haze.addColorStop(1,'rgba(135,190,255,.3)');ctx.fillStyle=haze;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.8)';ctx.font='25px serif';for(let i=0;i<24;i++)ctx.fillText(i%3?'✦':'♡',25+(i*137)%w,35+(i*83)%h)}if(effect==='candy'){const pop=ctx.createLinearGradient(0,h,w,0);pop.addColorStop(0,'rgba(255,55,170,.25)');pop.addColorStop(.5,'rgba(255,255,255,0)');pop.addColorStop(1,'rgba(40,210,255,.27)');ctx.fillStyle=pop;ctx.fillRect(0,0,w,h);ctx.font='30px serif';for(let i=0;i<12;i++)ctx.fillText(i%2?'★':'♥',20+(i*181)%w,45+(i*119)%h)}ctx.restore()}

export default function PhotoBooth({roomCode,userId,name,peers,gameEvents,sendGame}:{roomCode:string;userId:string;name:string;peers:Peer[];gameEvents:GameEvent[];sendGame:(type:string,data:unknown)=>void}){
  const booth=boothState(gameEvents);const[selected,setSelected]=useState<string[]>([]);const[prompt,setPrompt]=useState(prompts[0]);const[effect,setEffect]=useState<Effect>('digicam');const[wallpaper,setWallpaper]=useState<Wallpaper>('clouds');const[prop,setProp]=useState<Prop>('stars');const[gallery,setGallery]=useState<GalleryPhoto[]>([]);const[error,setError]=useState('');const[cameraError,setCameraError]=useState('');const[cameraReady,setCameraReady]=useState(false);const[requestingCamera,setRequestingCamera]=useState(false);const[composing,setComposing]=useState(false);const[,tick]=useState(0)
  const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const captured=useRef<string[]>([])
  const loadGallery=useCallback(async()=>{if(!supabase)return;const{data,error:e}=await supabase.from('lounge_photos').select('*').eq('room_code',roomCode).order('created_at',{ascending:false}).limit(24);if(e)setError(e.message);else setGallery((data||[]) as GalleryPhoto[])},[roomCode])
  useEffect(()=>{void loadGallery();const client=supabase;if(!client)return;const channel=client.channel(`photo-gallery:${roomCode}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'lounge_photos',filter:`room_code=eq.${roomCode}`},()=>void loadGallery()).subscribe();return()=>{void client.removeChannel(channel)}},[loadGallery,roomCode])
  const isInvited=Boolean(booth?.invited.some(p=>p.id===userId));const accepted=booth?.hostId===userId||booth?.accepted[userId]===true;const involved=booth?.hostId===userId||isInvited
  const startCamera=useCallback(async()=>{if(!navigator.mediaDevices?.getUserMedia){setCameraError(location.protocol==='https:'?'This browser does not provide camera access. Try a current version of Chrome, Edge or Safari.':'Camera access only works on HTTPS or localhost.');return}setRequestingCamera(true);setCameraError('');setCameraReady(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;let lastError:unknown;for(const constraints of [{video:{facingMode:'user'},audio:false},{video:true,audio:false}]){try{const next=await navigator.mediaDevices.getUserMedia(constraints);stream.current=next;if(video.current){video.current.srcObject=next;await video.current.play()}setCameraReady(true);setRequestingCamera(false);return}catch(e){lastError=e;if(e instanceof DOMException&&!['OverconstrainedError','AbortError'].includes(e.name))break}}const errorName=lastError instanceof DOMException?lastError.name:'';const messages:Record<string,string>={NotAllowedError:'Camera access is blocked for this site. Open the lock/camera icon in the address bar, allow access, then press Retry camera.',NotReadableError:'Permission is allowed, but the camera is busy. Close Camera, Zoom, Teams, or another browser tab and retry.',NotFoundError:'No usable camera was found on this device.',SecurityError:'The browser blocked camera access. Open the lounge over HTTPS and retry.',AbortError:'Camera startup was interrupted. Wait a moment and retry.',OverconstrainedError:'The selected camera could not satisfy the requested settings. Retry will use basic settings.'};setCameraError(messages[errorName]||`The camera could not start${errorName?` (${errorName})`:''}. Try closing other camera apps and retry.`);setRequestingCamera(false)},[])
  useEffect(()=>{if(!booth||!accepted||!['lobby','countdown','review'].includes(booth.status)){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCameraReady(false);return}void startCamera();return()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[booth?.id,accepted,startCamera])
  useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),200);return()=>clearInterval(timer)},[])
  const seconds=booth?.status==='countdown'&&booth.deadline?Math.max(0,Math.ceil((booth.deadline-Date.now())/1000)):0
  const uploadFrame=useCallback(async()=>{if(!booth||!video.current||!supabase||captured.current.includes(booth.id))return;captured.current.push(booth.id);try{const[wall,propsImage]=await Promise.all([loadImage('/booth-wallpapers.png'),loadImage('/booth-props.png')]);const canvas=document.createElement('canvas');canvas.width=960;canvas.height=720;const ctx=canvas.getContext('2d')!;drawWallpaper(ctx,wall,booth.wallpaper||'clouds',0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.roundRect(46,42,868,620,25);ctx.clip();ctx.filter=filters[booth.effect||'digicam'];ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(video.current,46,42,868,620);ctx.restore();ctx.filter='none';decorate(ctx,booth.effect||'digicam',canvas.width,canvas.height);drawProp(ctx,propsImage,booth.prop||'none',canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.92));if(!blob)throw new Error('Could not capture the frame.');const path=`${roomCode}/${booth.id}/${userId}.jpg`;const up=await supabase.storage.from('lounge-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(up.error)throw up.error;const{data}=supabase.storage.from('lounge-photos').getPublicUrl(path);sendGame('booth-shot',{session:booth.id,shot:{playerId:userId,name,url:data.publicUrl}})}catch(e){captured.current=captured.current.filter(id=>id!==booth.id);setError(e instanceof Error?e.message:'Could not capture the frame.')}},[booth,roomCode,userId,name,sendGame])
  useEffect(()=>{if(booth?.status==='countdown'&&seconds===0&&cameraReady)void uploadFrame()},[booth?.status,seconds,cameraReady,uploadFrame])
  const participants=useMemo(()=>booth?[{id:booth.hostId,name:booth.hostName},...booth.invited.filter(p=>booth.accepted[p.id])]:[],[booth])
  const allResponded=booth?booth.invited.every(p=>booth.accepted[p.id]!==undefined):false;const allShot=booth?participants.every(p=>booth.shots[p.id]):false
  const compose=async()=>{if(!booth||!supabase||!allShot)return;setComposing(true);try{const shots=participants.map(p=>booth.shots[p.id]);const images=await Promise.all(shots.map(s=>loadImage(s.url)));const wall=await loadImage('/booth-wallpapers.png');const cols=images.length===1?1:images.length<=4?2:3;const rows=Math.ceil(images.length/cols);const width=1200,cellW=width/cols,cellH=520,height=rows*cellH+190;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;drawWallpaper(ctx,wall,booth.wallpaper||'clouds',0,0,width,height);ctx.fillStyle='rgba(255,247,232,.3)';ctx.fillRect(0,0,width,height-190);images.forEach((img,i)=>{const x=i%cols*cellW,y=Math.floor(i/cols)*cellH;ctx.save();ctx.fillStyle='white';ctx.shadowColor='rgba(50,30,60,.3)';ctx.shadowBlur=15;ctx.fillRect(x+16,y+14,cellW-32,cellH-30);ctx.shadowBlur=0;ctx.beginPath();ctx.rect(x+28,y+26,cellW-56,cellH-82);ctx.clip();const scale=Math.max((cellW-56)/img.width,(cellH-82)/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,x+(cellW-w)/2,y+26+(cellH-82-h)/2,w,h);ctx.restore();ctx.fillStyle='#403b56';ctx.font='700 24px sans-serif';ctx.fillText(shots[i].name,x+30,y+cellH-20)});ctx.fillStyle='rgba(60,47,86,.94)';ctx.fillRect(0,height-190,width,190);ctx.fillStyle='#ffc777';ctx.font='700 26px sans-serif';ctx.fillText('THE COMMON LOUNGE PHOTOBOOTH',45,height-132);ctx.fillStyle='white';ctx.font='italic 42px serif';ctx.fillText(`“${booth.prompt}”`,45,height-72);ctx.font='20px sans-serif';ctx.fillText(`${booth.effect.toUpperCase()} • ${new Date().toLocaleString()}`,45,height-32);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.92));if(!blob)throw new Error('Could not compose photo.');const path=`${roomCode}/gallery/${booth.id}.jpg`;const up=await supabase.storage.from('lounge-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(up.error)throw up.error;const{data}=supabase.storage.from('lounge-photos').getPublicUrl(path);const saved=await supabase.from('lounge_photos').upsert({room_code:roomCode,session_id:booth.id,image_url:data.publicUrl,prompt:booth.prompt,effect:booth.effect,participants:participants.map(p=>p.name)},{onConflict:'session_id'});if(saved.error)throw saved.error;sendGame('booth-final',{session:booth.id,url:data.publicUrl});await loadGallery()}catch(e){setError(e instanceof Error?e.message:'Could not compose the group photo.')}finally{setComposing(false)}}
  const start=()=>{const invitees=peers.filter(p=>selected.includes(p.id)).map(p=>({id:p.id,name:p.name}));const id=crypto.randomUUID();sendGame('booth-start',{id,hostId:userId,hostName:name,invited:invitees,accepted:{[userId]:true},prompt,effect,wallpaper,prop,status:'lobby',shots:{}} satisfies Booth)}
  const activeWallpaper=booth?.wallpaper||'clouds',activeProp=booth?.prop||'none'
  return <div className="booth"><section className="booth-hero"><div><small>📸 THE REMOTE PHOTOBOOTH</small><h2>Different rooms.<br/>Same photograph.</h2><p>Pick a whole little world—not just a tint. Then invite friends into it.</p></div><div className="film-strip"><i/><i/><i/></div></section>{error&&<p className="data-error">{error}</p>}
  {!booth&&<section className="booth-setup"><h3>1. Pick a prompt</h3><label>Tonight's direction<select value={prompt} onChange={e=>setPrompt(e.target.value)}>{prompts.map(p=><option key={p}>{p}</option>)}</select></label><h3>2. Choose a real effect</h3><div className="effect-grid">{effects.map(([id,title,sub])=><button className={effect===id?'chosen':''} key={id} onClick={()=>setEffect(id)}><span className={'effect-preview '+id}/><b>{title}</b><small>{sub}</small></button>)}</div><h3>3. Step into a wallpaper</h3><div className="wallpaper-grid">{wallpapers.map(([id,title])=><button className={wallpaper===id?'chosen':''} key={id} onClick={()=>setWallpaper(id)}><span style={{backgroundPosition:wallpaperPosition(id)}}/><b>{title}</b></button>)}</div><h3>4. Add something silly</h3><div className="prop-grid">{props.map(([id,title])=><button className={prop===id?'chosen':''} key={id} onClick={()=>setProp(id)}><span className={id==='none'?'no-prop':''} style={id==='none'?undefined:{backgroundPosition:propPosition(id)}}>{id==='none'?'×':''}</span><b>{title}</b></button>)}</div><h3>5. Who is in this one?</h3><div className="online-invites">{peers.length===0?<p>Nobody else is online—take a solo picture or share the room link.</p>:peers.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/><span>{p.name[0]}</span>{p.name}</label>)}</div><button className="booth-primary" onClick={start}>{selected.length?`Invite ${selected.length} friend${selected.length>1?'s':''}`:'Take a solo photo'} →</button></section>}
  {booth&&isInvited&&booth.accepted[userId]===undefined&&<section className="booth-invite"><span>📷</span><h2>{booth.hostName} invited you to a photo</h2><p>“{booth.prompt}” · {booth.effect} · {activeWallpaper}</p><button onClick={()=>sendGame('booth-response',{session:booth.id,playerId:userId,accepted:true})}>Join the picture</button><button className="ghost" onClick={()=>sendGame('booth-response',{session:booth.id,playerId:userId,accepted:false})}>Not this one</button></section>}
  {booth&&!involved&&<section className="booth-wait"><h3>A private booth session is in progress</h3><p>{booth.hostName} invited selected friends. The gallery is still open below.</p></section>}
  {booth&&accepted&&booth.status!=='done'&&<section className="camera-stage"><div className={'camera-view '+booth.effect+' wallpaper-'+activeWallpaper}><video ref={video} autoPlay muted playsInline/><div className={'live-effect '+booth.effect}/>{activeProp!=='none'&&<div className={'prop-overlay prop-'+activeProp} style={{backgroundPosition:propPosition(activeProp)}}/>}<div className="viewfinder"/><span className="camera-prompt">{booth.prompt}</span>{!cameraReady&&!requestingCamera&&<button className="camera-enable" onClick={()=>void startCamera()}>Enable camera</button>}{requestingCamera&&<strong className="camera-loading">Starting camera…</strong>}{booth.status==='countdown'&&<strong className="camera-count">{seconds||'CLICK!'}</strong>}</div><div className="session-panel"><small>SESSION BY {booth.hostName.toUpperCase()}</small><h3>{booth.status==='lobby'?'Friends are joining…':booth.status==='countdown'?'Hold that pose!':'Frames received'}</h3><p className="vibe-receipt">{activeWallpaper} set · {booth.effect} · {activeProp}</p>{cameraError&&<div className="camera-error"><p>{cameraError}</p><button onClick={()=>void startCamera()}>Retry camera</button></div>}{cameraReady&&<p className="camera-ok">● Camera ready</p>}<div className="participant-list">{[{id:booth.hostId,name:booth.hostName},...booth.invited].map(p=><span key={p.id}>{booth.shots[p.id]?'✓':booth.accepted[p.id]===false?'×':booth.accepted[p.id]?'●':'○'} {p.name}</span>)}</div>{booth.hostId===userId&&booth.status==='lobby'&&<button className="booth-primary" disabled={!allResponded||!cameraReady} onClick={()=>sendGame('booth-launch',{session:booth.id,deadline:Date.now()+4000})}>Start 3-second countdown</button>}{booth.status==='countdown'&&seconds===0&&!booth.shots[userId]&&<button className="booth-primary" disabled={!cameraReady} onClick={()=>void uploadFrame()}>Retry my capture</button>}{booth.hostId===userId&&booth.status==='review'&&<button className="booth-primary" disabled={!allShot||composing} onClick={()=>void compose()}>{composing?'Developing…':'Develop group photo ✦'}</button>}{booth.status==='countdown'&&seconds===0&&!allShot&&<p>Waiting for every camera to send its frame…</p>}</div></section>}
  {booth?.status==='done'&&involved&&<section className="booth-result"><small>FRESH FROM THE DARKROOM</small><img src={booth.finalUrl} alt={`Photobooth: ${booth.prompt}`}/><div><a href={booth.finalUrl} download target="_blank" rel="noreferrer">Download photo</a><button onClick={()=>sendGame('booth-start',{id:crypto.randomUUID(),hostId:userId,hostName:name,invited:[],accepted:{[userId]:true},prompt:prompts[0],effect:'digicam',wallpaper:'clouds',prop:'stars',status:'lobby',shots:{}} satisfies Booth)}>New photo</button></div></section>}
  <section className="gallery"><div><small>ROOM {roomCode}</small><h2>Shared photo drawer</h2><p>Saved on the web for everyone with this room.</p></div>{gallery.length===0?<p className="empty-gallery">Your first developed photo will appear here.</p>:<div className="gallery-grid">{gallery.map(photo=><figure key={photo.id}><img src={photo.image_url} alt={photo.prompt}/><figcaption><b>{photo.prompt}</b><span>{photo.participants.join(' · ')}</span></figcaption></figure>)}</div>}</section></div>
}
