import { useCallback, useEffect, useState } from 'react'
import { supabase } from './supabaseClient'

type Post={id:string;room_code:string;author_id:string;author_name:string;body:string;created_at:string}
type Like={post_id:string;user_id:string}
type Reply={id:string;post_id:string;author_id:string;author_name:string;body:string;created_at:string}

export default function TeaBoard({roomCode,userId,name}:{roomCode:string;userId:string;name:string}){
  const[posts,setPosts]=useState<Post[]>([]);const[likes,setLikes]=useState<Like[]>([]);const[replies,setReplies]=useState<Reply[]>([])
  const[pin,setPin]=useState('');const[replying,setReplying]=useState<string>();const[reply,setReply]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  const load=useCallback(async()=>{if(!supabase){setError('Tea storage is not configured.');return}const[p,r]=await Promise.all([supabase.from('lounge_tea_posts').select('*').eq('room_code',roomCode).order('created_at',{ascending:false}),supabase.from('lounge_tea_replies').select('*').eq('room_code',roomCode).order('created_at')]);if(p.error||r.error){setError(p.error?.message||r.error?.message||'Could not load the tea board.');return}const postRows=(p.data||[]) as Post[];const ids=postRows.map(x=>x.id);let likeRows:Like[]=[];if(ids.length){const l=await supabase.from('lounge_tea_likes').select('post_id,user_id').in('post_id',ids);if(l.error){setError(l.error.message);return}likeRows=(l.data||[]) as Like[]}setPosts(postRows);setReplies((r.data||[]) as Reply[]);setLikes(likeRows);setError('')},[roomCode])
  useEffect(()=>{void load();const client=supabase;if(!client)return;const channel=client.channel(`tea-board:${roomCode}:${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'lounge_tea_posts',filter:`room_code=eq.${roomCode}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'lounge_tea_replies',filter:`room_code=eq.${roomCode}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'lounge_tea_likes'},()=>void load()).subscribe();return()=>{void client.removeChannel(channel)}},[load,roomCode,userId])
  const add=async()=>{if(!pin.trim()||!supabase)return;setBusy(true);const{error:e}=await supabase.from('lounge_tea_posts').insert({room_code:roomCode,author_id:userId,author_name:name,body:pin.trim()});setBusy(false);if(e)setError(e.message);else{setPin('');await load()}}
  const toggleLike=async(postId:string)=>{if(!supabase)return;const mine=likes.some(l=>l.post_id===postId&&l.user_id===userId);const q=mine?supabase.from('lounge_tea_likes').delete().eq('post_id',postId).eq('user_id',userId):supabase.from('lounge_tea_likes').insert({post_id:postId,user_id:userId});const{error:e}=await q;if(e)setError(e.message);else await load()}
  const addReply=async(postId:string)=>{if(!reply.trim()||!supabase)return;const{error:e}=await supabase.from('lounge_tea_replies').insert({post_id:postId,room_code:roomCode,author_id:userId,author_name:name,body:reply.trim()});if(e)setError(e.message);else{setReply('');setReplying(undefined);await load()}}
  return <><section className="tea-hero"><span>☕</span><div><h2>Tea board</h2><p>It stays after refresh now. Like it, reply to it, keep the lore alive.</p></div></section><form className="pin-form" onSubmit={e=>{e.preventDefault();void add()}}><input maxLength={500} value={pin} onChange={e=>setPin(e.target.value)} placeholder="What's the tea?"/><button disabled={busy||!pin.trim()}>Pin it ✦</button></form>{error&&<p className="data-error">{error}</p>}<div className="pins">{posts.map((post,i)=>{const postLikes=likes.filter(l=>l.post_id===post.id);const postReplies=replies.filter(r=>r.post_id===post.id);const mine=postLikes.some(l=>l.user_id===userId);return <article className={'pin p'+i%4} key={post.id}><span>☕ {post.author_name.toUpperCase()}</span><p>{post.body}</p><small>{new Date(post.created_at).toLocaleString()}</small><div className="tea-actions"><button className={mine?'liked':''} onClick={()=>void toggleLike(post.id)}>{mine?'♥':'♡'} {postLikes.length}</button><button onClick={()=>setReplying(replying===post.id?undefined:post.id)}>↩ Reply {postReplies.length||''}</button></div>{postReplies.length>0&&<div className="tea-replies">{postReplies.map(r=><p key={r.id}><b>{r.author_name}</b> {r.body}</p>)}</div>}{replying===post.id&&<form className="reply-form" onSubmit={e=>{e.preventDefault();void addReply(post.id)}}><input autoFocus maxLength={300} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Add a reply…"/><button>Post</button></form>}</article>})}</div></>
}
